version: "3"
services:
  client:
    container_name: client
    build:
      context: ../M5-Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - mongo
    volumes:
      - .:/app
    # networks:
    #   - networkThree

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
